spring:
    application:
        name: spider
        index: ${random.long}
server:
    port: 8087


target-web-page:
  mappings:
    - webpage:
      rootUrl: https://www.163.com
      rootRegex: "https://www.163.com"
      seedRegex: "https://news.163.com/\\d+/\\d+/\\d+/\\.*\\.html"
      templatePath: com.migu.template.WY163Template

#logging:
#  level:
#    root: DEBUG
